version: "2"

linters:
  default: standard
  enable:
    - paralleltest
    - thelper
    - whitespace

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 120

run:
  timeout: 5m
