name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      # To comment on PRs
      pull-requests: write
      # To retrieve test step time in GitHub Action
      contents: read
      # To retrieve previous report for default branch, which is saved as GitHub Action Artifacts
      actions: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run tests with coverage report output
        run: go test ./... -coverprofile=coverage.out
      - uses: k1LoW/octocov-action@v1
